# Generated by Django 5.1.7 on 2025-03-28 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='is_plublished',
            new_name='is_published',
        ),
    ]
